### ISSUE TITLE
MCALT atlas request

### ISSUE THREAD

**Issue by AnnHab** [ggsegverse/discussions#14]
Hi Mo,

I am a huge fan of the visualisation possibilities provided by ggseg and I am wondering whether the following atlas could be added to the toolbox:
https://www.nitrc.org/projects/mcalt/

Thank you in advance!

**Comment by drmowinckels** [comment]
Thank you for using ggseg and requesting a new atlas.

We are currently unable to set aside time to create new atlases, but will look into it when time allows.
If you are eager to get a new atlas prepped, we recommend trying the ggseg-atlas creation tools in the [ggsegExtra package](https://ggseg.github.io/ggsegExtra/articles/customatlas.html). Feedback on the process is much appreciated, as we hope this will make it possible for more people to create their own custom atlases.
